# Generated by Django 5.2.5 on 2025-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_count_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
