# Generated by Django 5.2.5 on 2025-08-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscription_last_count_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Automatically renew subscription?'),
        ),
    ]
