# Generated by Django 5.2.5 on 2025-08-21 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_publisher_borrow_librarymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
