# Generated by Django 5.2.5 on 2025-08-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_borrow_borrowed_at_alter_borrow_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
