# Generated by Django 5.2.5 on 2025-08-22 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_full_content_book_preview_content_bookaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_bio', models.TextField(blank=True)),
                ('book_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('manuscript', models.FileField(upload_to='submissions/')),
                ('payment_choice', models.CharField(choices=[('unlimited_fee', 'Yearly Unlimited Fee'), ('revshare_20', '20% Revenue Share')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='librarymember',
            name='borrowed_books',
        ),
        migrations.RemoveField(
            model_name='librarymember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.RenameField(
            model_name='bookaccess',
            old_name='date_accessed',
            new_name='first_opened',
        ),
        migrations.RemoveField(
            model_name='book',
            name='full_content',
        ),
        migrations.RemoveField(
            model_name='book',
            name='preview_content',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/files/'),
        ),
        migrations.AddField(
            model_name='book',
            name='full_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='month_key',
            field=models.CharField(default=8, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookaccess',
            unique_together={('user', 'book', 'month_key')},
        ),
        migrations.AddField(
            model_name='readinglist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LibraryMember',
        ),
        migrations.AlterUniqueTogether(
            name='readinglist',
            unique_together={('user', 'book')},
        ),
    ]
