# Generated by Django 5.2.5 on 2025-08-22 23:13

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_authorsubmission_readinglist_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookaccess',
            name='first_opened',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookaccess',
            name='month_key',
            field=models.IntegerField(default=books.models.current_month),
        ),
    ]
